packages:
  - apps/*
  - packages/*

catalog:
  '@cloudflare/workers-types': ^4.20260310.1
  '@libsql/client': 0.15.15
  '@orpc/client': ^1.12.2
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/zod': ^1.12.2
  '@types/node': ^22.19.15
  alchemy: ^0.82.2
  better-auth: ^1.4.18
  dotenv: ^17.3.1
  drizzle-orm: ^0.45.1
  hono: ^4.8.2
  libsql: 0.5.22
  typescript: ^5.9.3
  zod: ^4.3.6

ignoredBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - workerd
