/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectUsernameRouteImport } from './routes/select-username'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app/projects/$projectId/index'
import { Route as AppProjectsProjectIdBoardsBoardIdIndexRouteImport } from './routes/app/projects/$projectId/boards/$boardId/index'
import { Route as AppProjectsProjectIdBoardsBoardIdArchivedRouteImport } from './routes/app/projects/$projectId/boards/$boardId/archived'
import { Route as AppProjectsProjectIdBoardsBoardIdCardIdRouteImport } from './routes/app/projects/$projectId/boards/$boardId/$cardId'

const SelectUsernameRoute = SelectUsernameRouteImport.update({
  id: '/select-username',
  path: '/select-username',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProjectsProjectIdBoardsBoardIdIndexRoute =
  AppProjectsProjectIdBoardsBoardIdIndexRouteImport.update({
    id: '/projects/$projectId/boards/$boardId/',
    path: '/projects/$projectId/boards/$boardId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProjectsProjectIdBoardsBoardIdArchivedRoute =
  AppProjectsProjectIdBoardsBoardIdArchivedRouteImport.update({
    id: '/projects/$projectId/boards/$boardId/archived',
    path: '/projects/$projectId/boards/$boardId/archived',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProjectsProjectIdBoardsBoardIdCardIdRoute =
  AppProjectsProjectIdBoardsBoardIdCardIdRouteImport.update({
    id: '/projects/$projectId/boards/$boardId/$cardId',
    path: '/projects/$projectId/boards/$boardId/$cardId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/select-username': typeof SelectUsernameRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/boards/$boardId/$cardId': typeof AppProjectsProjectIdBoardsBoardIdCardIdRoute
  '/app/projects/$projectId/boards/$boardId/archived': typeof AppProjectsProjectIdBoardsBoardIdArchivedRoute
  '/app/projects/$projectId/boards/$boardId/': typeof AppProjectsProjectIdBoardsBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/select-username': typeof SelectUsernameRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/app': typeof AppIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/boards/$boardId/$cardId': typeof AppProjectsProjectIdBoardsBoardIdCardIdRoute
  '/app/projects/$projectId/boards/$boardId/archived': typeof AppProjectsProjectIdBoardsBoardIdArchivedRoute
  '/app/projects/$projectId/boards/$boardId': typeof AppProjectsProjectIdBoardsBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/select-username': typeof SelectUsernameRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/boards/$boardId/$cardId': typeof AppProjectsProjectIdBoardsBoardIdCardIdRoute
  '/app/projects/$projectId/boards/$boardId/archived': typeof AppProjectsProjectIdBoardsBoardIdArchivedRoute
  '/app/projects/$projectId/boards/$boardId/': typeof AppProjectsProjectIdBoardsBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/select-username'
    | '/profile/$username'
    | '/app/'
    | '/app/projects/'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/boards/$boardId/$cardId'
    | '/app/projects/$projectId/boards/$boardId/archived'
    | '/app/projects/$projectId/boards/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/select-username'
    | '/profile/$username'
    | '/app'
    | '/app/projects'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/boards/$boardId/$cardId'
    | '/app/projects/$projectId/boards/$boardId/archived'
    | '/app/projects/$projectId/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/select-username'
    | '/profile/$username'
    | '/app/'
    | '/app/projects/'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/boards/$boardId/$cardId'
    | '/app/projects/$projectId/boards/$boardId/archived'
    | '/app/projects/$projectId/boards/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  SelectUsernameRoute: typeof SelectUsernameRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-username': {
      id: '/select-username'
      path: '/select-username'
      fullPath: '/select-username'
      preLoaderRoute: typeof SelectUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$projectId/boards/$boardId/': {
      id: '/app/projects/$projectId/boards/$boardId/'
      path: '/projects/$projectId/boards/$boardId'
      fullPath: '/app/projects/$projectId/boards/$boardId/'
      preLoaderRoute: typeof AppProjectsProjectIdBoardsBoardIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$projectId/boards/$boardId/archived': {
      id: '/app/projects/$projectId/boards/$boardId/archived'
      path: '/projects/$projectId/boards/$boardId/archived'
      fullPath: '/app/projects/$projectId/boards/$boardId/archived'
      preLoaderRoute: typeof AppProjectsProjectIdBoardsBoardIdArchivedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$projectId/boards/$boardId/$cardId': {
      id: '/app/projects/$projectId/boards/$boardId/$cardId'
      path: '/projects/$projectId/boards/$boardId/$cardId'
      fullPath: '/app/projects/$projectId/boards/$boardId/$cardId'
      preLoaderRoute: typeof AppProjectsProjectIdBoardsBoardIdCardIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdBoardsBoardIdCardIdRoute: typeof AppProjectsProjectIdBoardsBoardIdCardIdRoute
  AppProjectsProjectIdBoardsBoardIdArchivedRoute: typeof AppProjectsProjectIdBoardsBoardIdArchivedRoute
  AppProjectsProjectIdBoardsBoardIdIndexRoute: typeof AppProjectsProjectIdBoardsBoardIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdBoardsBoardIdCardIdRoute:
    AppProjectsProjectIdBoardsBoardIdCardIdRoute,
  AppProjectsProjectIdBoardsBoardIdArchivedRoute:
    AppProjectsProjectIdBoardsBoardIdArchivedRoute,
  AppProjectsProjectIdBoardsBoardIdIndexRoute:
    AppProjectsProjectIdBoardsBoardIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  SelectUsernameRoute: SelectUsernameRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
