/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdBoardsBoardIdIndexRouteImport } from './routes/projects/$projectId/boards/$boardId/index'
import { Route as ProjectsProjectIdBoardsBoardIdArchivedRouteImport } from './routes/projects/$projectId/boards/$boardId/archived'
import { Route as ProjectsProjectIdBoardsBoardIdCardIdRouteImport } from './routes/projects/$projectId/boards/$boardId/$cardId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdBoardsBoardIdIndexRoute =
  ProjectsProjectIdBoardsBoardIdIndexRouteImport.update({
    id: '/projects/$projectId/boards/$boardId/',
    path: '/projects/$projectId/boards/$boardId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdBoardsBoardIdArchivedRoute =
  ProjectsProjectIdBoardsBoardIdArchivedRouteImport.update({
    id: '/projects/$projectId/boards/$boardId/archived',
    path: '/projects/$projectId/boards/$boardId/archived',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdBoardsBoardIdCardIdRoute =
  ProjectsProjectIdBoardsBoardIdCardIdRouteImport.update({
    id: '/projects/$projectId/boards/$boardId/$cardId',
    path: '/projects/$projectId/boards/$boardId/$cardId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/boards/$boardId/$cardId': typeof ProjectsProjectIdBoardsBoardIdCardIdRoute
  '/projects/$projectId/boards/$boardId/archived': typeof ProjectsProjectIdBoardsBoardIdArchivedRoute
  '/projects/$projectId/boards/$boardId/': typeof ProjectsProjectIdBoardsBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/boards/$boardId/$cardId': typeof ProjectsProjectIdBoardsBoardIdCardIdRoute
  '/projects/$projectId/boards/$boardId/archived': typeof ProjectsProjectIdBoardsBoardIdArchivedRoute
  '/projects/$projectId/boards/$boardId': typeof ProjectsProjectIdBoardsBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/boards/$boardId/$cardId': typeof ProjectsProjectIdBoardsBoardIdCardIdRoute
  '/projects/$projectId/boards/$boardId/archived': typeof ProjectsProjectIdBoardsBoardIdArchivedRoute
  '/projects/$projectId/boards/$boardId/': typeof ProjectsProjectIdBoardsBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/profile/$username'
    | '/projects/'
    | '/projects/$projectId/'
    | '/projects/$projectId/boards/$boardId/$cardId'
    | '/projects/$projectId/boards/$boardId/archived'
    | '/projects/$projectId/boards/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/profile/$username'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/boards/$boardId/$cardId'
    | '/projects/$projectId/boards/$boardId/archived'
    | '/projects/$projectId/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/profile/$username'
    | '/projects/'
    | '/projects/$projectId/'
    | '/projects/$projectId/boards/$boardId/$cardId'
    | '/projects/$projectId/boards/$boardId/archived'
    | '/projects/$projectId/boards/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdBoardsBoardIdCardIdRoute: typeof ProjectsProjectIdBoardsBoardIdCardIdRoute
  ProjectsProjectIdBoardsBoardIdArchivedRoute: typeof ProjectsProjectIdBoardsBoardIdArchivedRoute
  ProjectsProjectIdBoardsBoardIdIndexRoute: typeof ProjectsProjectIdBoardsBoardIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/boards/$boardId/': {
      id: '/projects/$projectId/boards/$boardId/'
      path: '/projects/$projectId/boards/$boardId'
      fullPath: '/projects/$projectId/boards/$boardId/'
      preLoaderRoute: typeof ProjectsProjectIdBoardsBoardIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/boards/$boardId/archived': {
      id: '/projects/$projectId/boards/$boardId/archived'
      path: '/projects/$projectId/boards/$boardId/archived'
      fullPath: '/projects/$projectId/boards/$boardId/archived'
      preLoaderRoute: typeof ProjectsProjectIdBoardsBoardIdArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/boards/$boardId/$cardId': {
      id: '/projects/$projectId/boards/$boardId/$cardId'
      path: '/projects/$projectId/boards/$boardId/$cardId'
      fullPath: '/projects/$projectId/boards/$boardId/$cardId'
      preLoaderRoute: typeof ProjectsProjectIdBoardsBoardIdCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdBoardsBoardIdCardIdRoute:
    ProjectsProjectIdBoardsBoardIdCardIdRoute,
  ProjectsProjectIdBoardsBoardIdArchivedRoute:
    ProjectsProjectIdBoardsBoardIdArchivedRoute,
  ProjectsProjectIdBoardsBoardIdIndexRoute:
    ProjectsProjectIdBoardsBoardIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
